import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { useState } from 'react';
import { useToast } from './Toast';
export function BulkActionBar({ selectedIds, collections, onClear, onDelete, onArchive, onAddToCollection, onAddTag }) {
    const [showCollPicker, setShowCollPicker] = useState(false);
    const [showTagInput, setShowTagInput] = useState(false);
    const [tagValue, setTagValue] = useState('');
    const [confirmDelete, setConfirmDelete] = useState(false);
    const { toast } = useToast();
    if (selectedIds.length === 0)
        return null;
    return (_jsxs("div", { className: "fixed bottom-6 left-1/2 -translate-x-1/2 z-40\n                    flex items-center gap-2 px-4 py-2.5 bg-surface-2\n                    border border-surface-4 rounded-2xl shadow-2xl\n                    shadow-black/40 backdrop-blur-sm", children: [_jsxs("span", { className: "text-xs font-medium text-ink-1 mr-1", children: [selectedIds.length, " selected"] }), _jsx("div", { className: "w-px h-4 bg-surface-4" }), _jsxs("div", { className: "relative", children: [_jsxs("button", { onClick: () => { setShowCollPicker(!showCollPicker); setShowTagInput(false); }, className: "flex items-center gap-1.5 px-2.5 py-1.5 text-xs text-ink-2\n                     hover:text-ink-1 hover:bg-surface-3 rounded-lg transition-colors", children: [_jsx("svg", { className: "w-3 h-3", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, children: _jsx("path", { d: "M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z" }) }), "Add to collection"] }), showCollPicker && (_jsx("div", { className: "absolute bottom-full mb-2 left-0 w-48 bg-surface-2\n                          border border-surface-4 rounded-xl overflow-hidden\n                          shadow-xl", children: collections.length === 0 ? (_jsx("p", { className: "text-[10px] text-ink-4 p-3 text-center", children: "No collections yet" })) : (collections.map(col => (_jsxs("button", { onClick: () => {
                                onAddToCollection(selectedIds, col.id);
                                setShowCollPicker(false);
                            }, className: "w-full flex items-center gap-2 px-3 py-2 text-left\n                             text-xs text-ink-2 hover:bg-surface-3 transition-colors", children: [_jsx("span", { children: col.icon }), _jsx("span", { className: "truncate", children: col.name })] }, col.id)))) }))] }), _jsxs("div", { className: "relative", children: [_jsxs("button", { onClick: () => { setShowTagInput(!showTagInput); setShowCollPicker(false); }, className: "flex items-center gap-1.5 px-2.5 py-1.5 text-xs text-ink-2\n                     hover:text-ink-1 hover:bg-surface-3 rounded-lg transition-colors", children: [_jsxs("svg", { className: "w-3 h-3", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, children: [_jsx("path", { d: "M20.59 13.41l-7.17 7.17a2 2 0 01-2.83 0L2 12V2h10l8.59 8.59a2 2 0 010 2.82z" }), _jsx("line", { x1: "7", y1: "7", x2: "7.01", y2: "7" })] }), "Tag all"] }), showTagInput && (_jsxs("div", { className: "absolute bottom-full mb-2 left-0 w-44 bg-surface-2\n                          border border-surface-4 rounded-xl p-2 shadow-xl", children: [_jsx("input", { autoFocus: true, type: "text", placeholder: "Tag name...", value: tagValue, onChange: e => setTagValue(e.target.value), onKeyDown: e => {
                                    if (e.key === 'Enter' && tagValue.trim()) {
                                        onAddTag(selectedIds, tagValue.trim());
                                        setTagValue('');
                                        setShowTagInput(false);
                                    }
                                    if (e.key === 'Escape')
                                        setShowTagInput(false);
                                }, className: "w-full px-2 py-1.5 bg-surface-3 border border-surface-4\n                         rounded-lg text-xs text-ink-1 outline-none focus:border-brand\n                         placeholder-ink-4" }), _jsx("p", { className: "text-[9px] text-ink-5 mt-1 text-center", children: "Enter to apply" })] }))] }), _jsxs("button", { onClick: () => { onArchive(selectedIds); onClear(); }, className: "flex items-center gap-1.5 px-2.5 py-1.5 text-xs text-ink-2\n                   hover:text-ink-1 hover:bg-surface-3 rounded-lg transition-colors", children: [_jsx("span", { children: "\uD83D\uDCE6" }), "Archive"] }), confirmDelete ? (_jsxs("div", { className: "flex items-center gap-1", children: [_jsxs("span", { className: "text-[10px] text-ink-3", children: ["Delete ", selectedIds.length, "?"] }), _jsx("button", { onClick: () => { onDelete(selectedIds); onClear(); setConfirmDelete(false); }, className: "text-[10px] text-red-400 px-2 py-1 hover:bg-red-400/10 rounded", children: "Yes" }), _jsx("button", { onClick: () => setConfirmDelete(false), className: "text-[10px] text-ink-3 hover:text-ink-1 px-1", children: "No" })] })) : (_jsxs("button", { onClick: () => setConfirmDelete(true), className: "flex items-center gap-1.5 px-2.5 py-1.5 text-xs text-red-400\n                     hover:bg-red-400/10 rounded-lg transition-colors", children: [_jsxs("svg", { className: "w-3 h-3", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 2, children: [_jsx("polyline", { points: "3 6 5 6 21 6" }), _jsx("path", { d: "M19 6l-1 14H6L5 6" })] }), "Delete"] })), _jsx("div", { className: "w-px h-4 bg-surface-4" }), _jsx("button", { onClick: onClear, className: "text-[10px] text-ink-4 hover:text-ink-2 transition-colors px-1", children: "\u2715 Clear" })] }));
}
